# Generated by Django 5.0.6 on 2024-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description_short', models.CharField(max_length=50)),
                ('description_long', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='product_images')),
                ('category', models.CharField(choices=[('SB', 'Shirts And Blouses'), ('TS', 'T-Shirts'), ('trending', 'trending'), ('HS', 'Hoodies&Sweatshirts'), ('men', 'men'), ('women', 'women'), ('kids', 'kids'), ('sports', 'sports'), ('tailor', 'tailor')], max_length=100)),
            ],
        ),
    ]
