# Generated by Django 5.0.6 on 2024-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_slide',
            field=models.ImageField(null=True, upload_to='slide_product_images'),
        ),
    ]
