# Generated by Django 5.0.6 on 2024-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_slide',
            new_name='image_slide1',
        ),
        migrations.AddField(
            model_name='category',
            name='image_slide2',
            field=models.ImageField(null=True, upload_to='slide_product_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_slide3',
            field=models.ImageField(null=True, upload_to='slide_product_images'),
        ),
    ]
