# Generated by Django 5.0.6 on 2024-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_slide_category_image_slide1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slide1', models.ImageField(null=True, upload_to='slide_product_images')),
                ('image_slide2', models.ImageField(null=True, upload_to='slide_product_images')),
                ('image_slide3', models.ImageField(null=True, upload_to='slide_product_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_slide1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_slide2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_slide3',
        ),
    ]
