# Generated by Django 5.0.6 on 2024-07-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_slides_remove_category_image_slide1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='products.category'),
            preserve_default=False,
        ),
    ]
